# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d87ad9e9903afeadbe7c4fce9f5fc6b9fd6911ef7eb60861666f78a62af8e4304998c0b04c0c6408dd288c927fce54fc547c01e7bb913b2f895f38608f1e7705

test:
  secret_key_base: 71a4b29fadb9e5d5aa32e64a215cdbcdc790dee09135b916d7c27c03812a658f1d55d440ba75d448d4bb202719079edc559f7d2a4503e37f062e3f73eb3bb799

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
